CREATE TABLE `CLIENTE` (
  `RUT_CLIENTE` VARCHAR(10) PRIMARY KEY,
  `DV` char(1) NOT NULL,
  `RAZON_SOCIAL` varchar(60) NOT NULL,
  `CORREO` varchar(50) NOT NULL,
  `TELEFONO` varchar(12),
  `ACTIVO` char(1) NOT NULL
);

CREATE TABLE `DOCUMENTO` (
  `ID_DOCUMENTO` int PRIMARY KEY AUTO_INCREMENT,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `FECHA_SUBIDA` datetime NOT NULL,
  `TIPO_MIME` varchar(50) NOT NULL,
  `ARCHIVO` LONGBLOB NOT NULL,
  `TAMANO_BYTES` int NOT NULL,
  `FK_RUT_CLIENTE` VARCHAR(10) NOT NULL
);

CREATE TABLE `ORDEN` (
  `ID_ORDEN` int PRIMARY KEY AUTO_INCREMENT,
  `HORAS_TRABAJO` INT NOT NULL,
  `FECHA_REGISTRO` datetime NOT NULL,
  `FECHA_AGENDADA` datetime NOT NULL,
  `FECHA_FINALIZADO` datetime NOT NULL,
  `OBSERVACION` varchar(100),
  `DIRECCION` varchar(50) NOT NULL,
  `FOLIO` int UNIQUE NOT NULL,
  `FK_COMUNA` int NOT NULL,
  `FK_RUT_CLIENTES` VARCHAR(10) NOT NULL,
  `FK_PATENTE` VARCHAR(8) NOT NULL,
  `FK_ESTADO` INT NOT NULL
);

CREATE TABLE `ORDEN_EMPLEADO` (
  `FK_ID_ORDENES` int NOT NULL,
  `FK_RUT_EMPLEADO` VARCHAR(10) NOT NULL
);

CREATE TABLE `EMPLEADO` (
  `RUT_EMPLEADO` VARCHAR(10) PRIMARY KEY,
  `DV` CHAR(1) NOT NULL,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `APELLIDO` VARCHAR(50) NOT NULL,
  `DIRECCION` varchar(50),
  `TELEFONO` varchar(12),
  `ACTIVO` char(1) NOT NULL,
  `FK_COMUNA` INT
);

CREATE TABLE `VEHICULO` (
  `PATENTE` VARCHAR(8) PRIMARY KEY,
  `CAPACIDAD` int NOT NULL,
  `ACTIVO` char(1) NOT NULL,
  `FK_TIPO` int NOT NULL
);

CREATE TABLE `TIPO_CARGA` (
  `TIPO_CARGA_CODIGO` int PRIMARY KEY AUTO_INCREMENT,
  `NOMBRE_CARGA` varchar(50) NOT NULL
);

CREATE TABLE `COMUNA` (
  `CODIGO` INT PRIMARY KEY,
  `NOMBRE` varchar(50) NOT NULL,
  `FK_CODIGO_REGION` INT NOT NULL
);

CREATE TABLE `REGION` (
  `CODIGO` INT PRIMARY KEY,
  `NOMBRE` varchar(50) NOT NULL
);

CREATE TABLE `USUARIO` (
  `ID_USUARIO` INT PRIMARY KEY AUTO_INCREMENT,
  `CORREO` varchar(50) UNIQUE NOT NULL,
  `PASSWORD` char(100) NOT NULL,
  `ACTIVO` int NOT NULL,
  `FK_ID_ROL` int NOT NULL,
  `FK_RUT_EMPLEADO` varchar(10)
);

CREATE TABLE `ROL` (
  `ID_ROL` INT PRIMARY KEY AUTO_INCREMENT,
  `NOMBRE` varchar(40) NOT NULL
);

CREATE TABLE `ORDEN_ESTADO` (
  `ID_ESTADO` int PRIMARY KEY AUTO_INCREMENT,
  `NOMBRE` varchar(30)
);

CREATE TABLE `REPORTE` (
  `ID_REPORTE` int PRIMARY KEY AUTO_INCREMENT,
  `OBSERVACION` varchar(100),
  `FK_USUARIO` int NOT NULL,
  `FK_ID_ORDEN` int NOT NULL,
  `FK_TIPO` int NOT NULL
);

CREATE TABLE `REPORTE_TIPO` (
  `CODIGO` INT PRIMARY KEY AUTO_INCREMENT,
  `NOMBRE` varchar(30) NOT NULL
);

CREATE TABLE `IMAGENES_REPORTE` (
  `ID_IMG_REPORTE` int PRIMARY KEY AUTO_INCREMENT,
  `TIPO_MIME` varchar(50) NOT NULL,
  `ARCHIVO` LONGBLOB NOT NULL,
  `FK_ID_REPORTE` int NOT NULL
);

ALTER TABLE `ORDEN` ADD CONSTRAINT `ORDEN_ESTADO` FOREIGN KEY (`FK_ESTADO`) REFERENCES `ORDEN_ESTADO` (`ID_ESTADO`);

ALTER TABLE `IMAGENES_REPORTE` ADD CONSTRAINT `REPORTE_IMAGENES` FOREIGN KEY (`FK_ID_REPORTE`) REFERENCES `REPORTE` (`ID_REPORTE`);

ALTER TABLE `REPORTE` ADD CONSTRAINT `ORDEN_REPORTE` FOREIGN KEY (`FK_ID_ORDEN`) REFERENCES `ORDEN` (`ID_ORDEN`);

ALTER TABLE `DOCUMENTO` ADD CONSTRAINT `DOCUMENTOS_CLIENTES` FOREIGN KEY (`FK_RUT_CLIENTE`) REFERENCES `CLIENTE` (`RUT_CLIENTE`);

ALTER TABLE `ORDEN` ADD CONSTRAINT `ORDENES_CLIENTES` FOREIGN KEY (`FK_RUT_CLIENTES`) REFERENCES `CLIENTE` (`RUT_CLIENTE`);

ALTER TABLE `ORDEN_EMPLEADO` ADD CONSTRAINT `OxE_ORDENES` FOREIGN KEY (`FK_ID_ORDENES`) REFERENCES `ORDEN` (`ID_ORDEN`);

ALTER TABLE `ORDEN_EMPLEADO` ADD CONSTRAINT `OxE_EMPLEADOS` FOREIGN KEY (`FK_RUT_EMPLEADO`) REFERENCES `EMPLEADO` (`RUT_EMPLEADO`);

ALTER TABLE `EMPLEADO` ADD CONSTRAINT `EMPLEADOS_COMUNA` FOREIGN KEY (`FK_COMUNA`) REFERENCES `COMUNA` (`CODIGO`);

ALTER TABLE `ORDEN` ADD CONSTRAINT `ORDENES_VEHICULOS` FOREIGN KEY (`FK_PATENTE`) REFERENCES `VEHICULO` (`PATENTE`);

ALTER TABLE `ORDEN` ADD CONSTRAINT `ORDENES_COMUNA` FOREIGN KEY (`FK_COMUNA`) REFERENCES `COMUNA` (`CODIGO`);

ALTER TABLE `VEHICULO` ADD CONSTRAINT `VEHICULO_TIPO_CARGA` FOREIGN KEY (`FK_TIPO`) REFERENCES `TIPO_CARGA` (`TIPO_CARGA_CODIGO`);

ALTER TABLE `COMUNA` ADD CONSTRAINT `REGION_COMUNA` FOREIGN KEY (`FK_CODIGO_REGION`) REFERENCES `REGION` (`CODIGO`);

ALTER TABLE `USUARIO` ADD CONSTRAINT `EMPLEADO_USUARIO` FOREIGN KEY (`FK_RUT_EMPLEADO`) REFERENCES `EMPLEADO` (`RUT_EMPLEADO`);

ALTER TABLE `USUARIO` ADD CONSTRAINT `USUARIO_ROL` FOREIGN KEY (`FK_ID_ROL`) REFERENCES `ROL` (`ID_ROL`);

ALTER TABLE `REPORTE` ADD CONSTRAINT `REPORT_REPORTE_TIPO` FOREIGN KEY (`FK_TIPO`) REFERENCES `REPORTE_TIPO` (`CODIGO`);

ALTER TABLE `REPORTE` ADD CONSTRAINT `USUARIO_REPORTE` FOREIGN KEY (`FK_USUARIO`) REFERENCES `USUARIO` (`ID_USUARIO`);
